version: "3.4"
services:
  pulseaudio:
    image: multiroom-server-pulseaudio
    build: ./pulseaudio
    ports:
      - "1704:1704"
      - "1705:1705"
    expose:
      - "4713"

  librespot:
    image: multiroom-server-librespot
    build: ./librespot
    depends_on:
      - pulseaudio
    env_file: ./librespot.env
